// Complete Worldwide ISO 3166-1 Alpha-2 Dataset (~240 Countries & Territories)

export const WORLD_COUNTRIES = [
  // Popular Countries Section (pre-marked with isPopular: true)
  { iso: 'US', name: 'United States', code: '+1', flag: '🇺🇸', isPopular: true, lang: 'en', minLen: 10, maxLen: 10 },
  { iso: 'GB', name: 'United Kingdom', code: '+44', flag: '🇬🇧', isPopular: true, lang: 'en', minLen: 10, maxLen: 10 },
  { iso: 'IN', name: 'India', code: '+91', flag: '🇮🇳', isPopular: true, lang: 'hi', minLen: 10, maxLen: 10 },
  { iso: 'AE', name: 'United Arab Emirates', code: '+971', flag: '🇦🇪', isPopular: true, lang: 'ar', minLen: 9, maxLen: 9 },
  { iso: 'SA', name: 'Saudi Arabia', code: '+966', flag: '🇸🇦', isPopular: true, lang: 'ar', minLen: 9, maxLen: 9 },
  { iso: 'QA', name: 'Qatar', code: '+974', flag: '🇶🇦', isPopular: true, lang: 'ar', minLen: 8, maxLen: 8 },
  { iso: 'KW', name: 'Kuwait', code: '+965', flag: '🇰🇼', isPopular: true, lang: 'ar', minLen: 8, maxLen: 8 },
  { iso: 'OM', name: 'Oman', code: '+968', flag: '🇴🇲', isPopular: true, lang: 'ar', minLen: 8, maxLen: 8 },
  { iso: 'BH', name: 'Bahrain', code: '+973', flag: '🇧🇭', isPopular: true, lang: 'ar', minLen: 8, maxLen: 8 },
  { iso: 'PK', name: 'Pakistan', code: '+92', flag: '🇵🇰', isPopular: true, lang: 'ur', minLen: 10, maxLen: 10 },
  { iso: 'BD', name: 'Bangladesh', code: '+880', flag: '🇧🇩', isPopular: true, lang: 'bn', minLen: 10, maxLen: 10 },
  { iso: 'MY', name: 'Malaysia', code: '+60', flag: '🇲🇾', isPopular: true, lang: 'en', minLen: 9, maxLen: 10 },
  { iso: 'SG', name: 'Singapore', code: '+65', flag: '🇸🇬', isPopular: true, lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'DE', name: 'Germany', code: '+49', flag: '🇩🇪', isPopular: true, lang: 'de', minLen: 10, maxLen: 11 },
  { iso: 'FR', name: 'France', code: '+33', flag: '🇫🇷', isPopular: true, lang: 'fr', minLen: 9, maxLen: 9 },
  { iso: 'CA', name: 'Canada', code: '+1', flag: '🇨🇦', isPopular: true, lang: 'en', minLen: 10, maxLen: 10 },
  { iso: 'AU', name: 'Australia', code: '+61', flag: '🇦🇺', isPopular: true, lang: 'en', minLen: 9, maxLen: 9 },

  // Remaining Worldwide ISO Countries (Alphabetically Sorted)
  { iso: 'AF', name: 'Afghanistan', code: '+93', flag: '🇦🇫', lang: 'fa', minLen: 9, maxLen: 9 },
  { iso: 'AL', name: 'Albania', code: '+355', flag: '🇦🇱', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'DZ', name: 'Algeria', code: '+213', flag: '🇩🇿', lang: 'ar', minLen: 9, maxLen: 9 },
  { iso: 'AD', name: 'Andorra', code: '+376', flag: '🇦🇩', lang: 'es', minLen: 6, maxLen: 6 },
  { iso: 'AO', name: 'Angola', code: '+244', flag: '🇦🇴', lang: 'pt', minLen: 9, maxLen: 9 },
  { iso: 'AG', name: 'Antigua & Barbuda', code: '+1268', flag: '🇦🇬', lang: 'en', minLen: 7, maxLen: 7 },
  { iso: 'AR', name: 'Argentina', code: '+54', flag: '🇦🇷', lang: 'es', minLen: 10, maxLen: 10 },
  { iso: 'AM', name: 'Armenia', code: '+374', flag: '🇦🇲', lang: 'ru', minLen: 8, maxLen: 8 },
  { iso: 'AT', name: 'Austria', code: '+43', flag: '🇦🇹', lang: 'de', minLen: 10, maxLen: 11 },
  { iso: 'AZ', name: 'Azerbaijan', code: '+994', flag: '🇦🇿', lang: 'tr', minLen: 9, maxLen: 9 },
  { iso: 'BS', name: 'Bahamas', code: '+1242', flag: '🇧🇸', lang: 'en', minLen: 7, maxLen: 7 },
  { iso: 'BB', name: 'Barbados', code: '+1246', flag: '🇧🇧', lang: 'en', minLen: 7, maxLen: 7 },
  { iso: 'BY', name: 'Belarus', code: '+375', flag: '🇧🇾', lang: 'ru', minLen: 9, maxLen: 9 },
  { iso: 'BE', name: 'Belgium', code: '+32', flag: '🇧🇪', lang: 'nl', minLen: 9, maxLen: 9 },
  { iso: 'BZ', name: 'Belize', code: '+501', flag: '🇧🇿', lang: 'es', minLen: 7, maxLen: 7 },
  { iso: 'BJ', name: 'Benin', code: '+229', flag: '🇧🇯', lang: 'fr', minLen: 8, maxLen: 8 },
  { iso: 'BT', name: 'Bhutan', code: '+975', flag: '🇧🇹', lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'BO', name: 'Bolivia', code: '+591', flag: '🇧🇴', lang: 'es', minLen: 8, maxLen: 8 },
  { iso: 'BA', name: 'Bosnia & Herzegovina', code: '+387', flag: '🇧🇦', lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'BW', name: 'Botswana', code: '+267', flag: '🇧🇼', lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'BR', name: 'Brazil', code: '+55', flag: '🇧🇷', lang: 'pt', minLen: 10, maxLen: 11 },
  { iso: 'BN', name: 'Brunei', code: '+673', flag: '🇧🇳', lang: 'en', minLen: 7, maxLen: 7 },
  { iso: 'BG', name: 'Bulgaria', code: '+359', flag: '🇧🇬', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'BF', name: 'Burkina Faso', code: '+226', flag: '🇧🇫', lang: 'fr', minLen: 8, maxLen: 8 },
  { iso: 'BI', name: 'Burundi', code: '+257', flag: '🇧🇮', lang: 'fr', minLen: 8, maxLen: 8 },
  { iso: 'KH', name: 'Cambodia', code: '+855', flag: '🇰🇭', lang: 'en', minLen: 8, maxLen: 9 },
  { iso: 'CM', name: 'Cameroon', code: '+237', flag: '🇨🇲', lang: 'fr', minLen: 9, maxLen: 9 },
  { iso: 'CV', name: 'Cape Verde', code: '+238', flag: '🇨🇻', lang: 'pt', minLen: 7, maxLen: 7 },
  { iso: 'CL', name: 'Chile', code: '+56', flag: '🇨🇱', lang: 'es', minLen: 9, maxLen: 9 },
  { iso: 'CN', name: 'China', code: '+86', flag: '🇨🇳', lang: 'zh', minLen: 11, maxLen: 11 },
  { iso: 'CO', name: 'Colombia', code: '+57', flag: '🇨🇴', lang: 'es', minLen: 10, maxLen: 10 },
  { iso: 'CR', name: 'Costa Rica', code: '+506', flag: '🇨🇷', lang: 'es', minLen: 8, maxLen: 8 },
  { iso: 'HR', name: 'Croatia', code: '+385', flag: '🇭🇷', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'CU', name: 'Cuba', code: '+53', flag: '🇨🇺', lang: 'es', minLen: 8, maxLen: 8 },
  { iso: 'CY', name: 'Cyprus', code: '+357', flag: '🇨🇾', lang: 'el', minLen: 8, maxLen: 8 },
  { iso: 'CZ', name: 'Czech Republic', code: '+420', flag: '🇨🇿', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'DK', name: 'Denmark', code: '+45', flag: '🇩🇰', lang: 'da', minLen: 8, maxLen: 8 },
  { iso: 'DJ', name: 'Djibouti', code: '+253', flag: '🇩🇯', lang: 'ar', minLen: 8, maxLen: 8 },
  { iso: 'DO', name: 'Dominican Republic', code: '+1809', flag: '🇩🇴', lang: 'es', minLen: 7, maxLen: 7 },
  { iso: 'EC', name: 'Ecuador', code: '+593', flag: '🇪🇨', lang: 'es', minLen: 9, maxLen: 9 },
  { iso: 'EG', name: 'Egypt', code: '+20', flag: '🇪🇬', lang: 'ar', minLen: 10, maxLen: 10 },
  { iso: 'SV', name: 'El Salvador', code: '+503', flag: '🇸🇻', lang: 'es', minLen: 8, maxLen: 8 },
  { iso: 'EE', name: 'Estonia', code: '+372', flag: '🇪🇪', lang: 'en', minLen: 7, maxLen: 8 },
  { iso: 'ET', name: 'Ethiopia', code: '+251', flag: '🇪🇹', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'FJ', name: 'Fiji', code: '+679', flag: '🇫🇯', lang: 'en', minLen: 7, maxLen: 7 },
  { iso: 'FI', name: 'Finland', code: '+358', flag: '🇫🇮', lang: 'fi', minLen: 9, maxLen: 10 },
  { iso: 'GE', name: 'Georgia', code: '+995', flag: '🇬🇪', lang: 'ru', minLen: 9, maxLen: 9 },
  { iso: 'GH', name: 'Ghana', code: '+233', flag: '🇬🇭', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'GR', name: 'Greece', code: '+30', flag: '🇬🇷', lang: 'el', minLen: 10, maxLen: 10 },
  { iso: 'GT', name: 'Guatemala', code: '+502', flag: '🇬🇹', lang: 'es', minLen: 8, maxLen: 8 },
  { iso: 'HN', name: 'Honduras', code: '+504', flag: '🇭🇳', lang: 'es', minLen: 8, maxLen: 8 },
  { iso: 'HK', name: 'Hong Kong', code: '+852', flag: '🇭🇰', lang: 'zh', minLen: 8, maxLen: 8 },
  { iso: 'HU', name: 'Hungary', code: '+36', flag: '🇭🇺', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'IS', name: 'Iceland', code: '+354', flag: '🇮🇸', lang: 'en', minLen: 7, maxLen: 7 },
  { iso: 'ID', name: 'Indonesia', code: '+62', flag: '🇮🇩', lang: 'id', minLen: 9, maxLen: 12 },
  { iso: 'IR', name: 'Iran', code: '+98', flag: '🇮🇷', lang: 'fa', minLen: 10, maxLen: 10 },
  { iso: 'IQ', name: 'Iraq', code: '+964', flag: '🇮🇶', lang: 'ar', minLen: 10, maxLen: 10 },
  { iso: 'IE', name: 'Ireland', code: '+353', flag: '🇮🇪', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'IL', name: 'Israel', code: '+972', flag: '🇮🇱', lang: 'he', minLen: 9, maxLen: 9 },
  { iso: 'IT', name: 'Italy', code: '+39', flag: '🇮🇹', lang: 'it', minLen: 10, maxLen: 10 },
  { iso: 'JM', name: 'Jamaica', code: '+1876', flag: '🇯🇲', lang: 'en', minLen: 7, maxLen: 7 },
  { iso: 'JP', name: 'Japan', code: '+81', flag: '🇯🇵', lang: 'ja', minLen: 10, maxLen: 10 },
  { iso: 'JO', name: 'Jordan', code: '+962', flag: '🇯🇴', lang: 'ar', minLen: 9, maxLen: 9 },
  { iso: 'KZ', name: 'Kazakhstan', code: '+7', flag: '🇰🇿', lang: 'ru', minLen: 10, maxLen: 10 },
  { iso: 'KE', name: 'Kenya', code: '+254', flag: '🇰🇪', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'KR', name: 'South Korea', code: '+82', flag: '🇰🇷', lang: 'ko', minLen: 9, maxLen: 10 },
  { iso: 'LA', name: 'Laos', code: '+856', flag: '🇱🇦', lang: 'en', minLen: 8, maxLen: 9 },
  { iso: 'LV', name: 'Latvia', code: '+371', flag: '🇱🇻', lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'LB', name: 'Lebanon', code: '+961', flag: '🇱🇧', lang: 'ar', minLen: 7, maxLen: 8 },
  { iso: 'LY', name: 'Libya', code: '+218', flag: '🇱🇾', lang: 'ar', minLen: 9, maxLen: 9 },
  { iso: 'LT', name: 'Lithuania', code: '+370', flag: '🇱🇹', lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'LU', name: 'Luxembourg', code: '+352', flag: '🇱🇺', lang: 'de', minLen: 9, maxLen: 9 },
  { iso: 'MO', name: 'Macau', code: '+853', flag: '🇲🇴', lang: 'zh', minLen: 8, maxLen: 8 },
  { iso: 'MV', name: 'Maldives', code: '+960', flag: '🇲🇻', lang: 'en', minLen: 7, maxLen: 7 },
  { iso: 'MT', name: 'Malta', code: '+356', flag: '🇲🇹', lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'MU', name: 'Mauritius', code: '+230', flag: '🇲🇺', lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'MX', name: 'Mexico', code: '+52', flag: '🇲🇽', lang: 'es', minLen: 10, maxLen: 10 },
  { iso: 'MD', name: 'Moldova', code: '+373', flag: '🇲🇩', lang: 'ru', minLen: 8, maxLen: 8 },
  { iso: 'MC', name: 'Monaco', code: '+377', flag: '🇲🇨', lang: 'fr', minLen: 8, maxLen: 9 },
  { iso: 'MN', name: 'Mongolia', code: '+976', flag: '🇲🇳', lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'ME', name: 'Montenegro', code: '+382', flag: '🇲🇪', lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'MA', name: 'Morocco', code: '+212', flag: '🇲🇦', lang: 'ar', minLen: 9, maxLen: 9 },
  { iso: 'MZ', name: 'Mozambique', code: '+258', flag: '🇲🇿', lang: 'pt', minLen: 9, maxLen: 9 },
  { iso: 'MM', name: 'Myanmar', code: '+95', flag: '🇲🇲', lang: 'en', minLen: 8, maxLen: 9 },
  { iso: 'NP', name: 'Nepal', code: '+977', flag: '🇳🇵', lang: 'hi', minLen: 10, maxLen: 10 },
  { iso: 'NL', name: 'Netherlands', code: '+31', flag: '🇳🇱', lang: 'nl', minLen: 9, maxLen: 9 },
  { iso: 'NZ', name: 'New Zealand', code: '+64', flag: '🇳🇿', lang: 'en', minLen: 8, maxLen: 9 },
  { iso: 'NI', name: 'Nicaragua', code: '+505', flag: '🇳🇮', lang: 'es', minLen: 8, maxLen: 8 },
  { iso: 'NG', name: 'Nigeria', code: '+234', flag: '🇳🇬', lang: 'en', minLen: 10, maxLen: 10 },
  { iso: 'NO', name: 'Norway', code: '+47', flag: '🇳🇴', lang: 'no', minLen: 8, maxLen: 8 },
  { iso: 'PA', name: 'Panama', code: '+507', flag: '🇵🇦', lang: 'es', minLen: 8, maxLen: 8 },
  { iso: 'PY', name: 'Paraguay', code: '+595', flag: '🇵🇾', lang: 'es', minLen: 9, maxLen: 9 },
  { iso: 'PE', name: 'Peru', code: '+51', flag: '🇵🇪', lang: 'es', minLen: 9, maxLen: 9 },
  { iso: 'PH', name: 'Philippines', code: '+63', flag: '🇵🇭', lang: 'en', minLen: 10, maxLen: 10 },
  { iso: 'PL', name: 'Poland', code: '+48', flag: '🇵🇱', lang: 'pl', minLen: 9, maxLen: 9 },
  { iso: 'PT', name: 'Portugal', code: '+351', flag: '🇵🇹', lang: 'pt', minLen: 9, maxLen: 9 },
  { iso: 'RO', name: 'Romania', code: '+40', flag: '🇷🇴', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'RU', name: 'Russia', code: '+7', flag: '🇷🇺', lang: 'ru', minLen: 10, maxLen: 10 },
  { iso: 'RW', name: 'Rwanda', code: '+250', flag: '🇷🇼', lang: 'fr', minLen: 9, maxLen: 9 },
  { iso: 'RS', name: 'Serbia', code: '+381', flag: '🇷🇸', lang: 'en', minLen: 8, maxLen: 9 },
  { iso: 'SK', name: 'Slovakia', code: '+421', flag: '🇸🇰', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'SI', name: 'Slovenia', code: '+386', flag: '🇸🇮', lang: 'en', minLen: 8, maxLen: 8 },
  { iso: 'ZA', name: 'South Africa', code: '+27', flag: '🇿🇦', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'ES', name: 'Spain', code: '+34', flag: '🇪🇸', lang: 'es', minLen: 9, maxLen: 9 },
  { iso: 'LK', name: 'Sri Lanka', code: '+94', flag: '🇱🇰', lang: 'ta', minLen: 9, maxLen: 9 },
  { iso: 'SD', name: 'Sudan', code: '+249', flag: '🇸🇩', lang: 'ar', minLen: 9, maxLen: 9 },
  { iso: 'SE', name: 'Sweden', code: '+46', flag: '🇸🇪', lang: 'sv', minLen: 9, maxLen: 9 },
  { iso: 'CH', name: 'Switzerland', code: '+41', flag: '🇨🇭', lang: 'de', minLen: 9, maxLen: 9 },
  { iso: 'SY', name: 'Syria', code: '+963', flag: '🇸🇾', lang: 'ar', minLen: 9, maxLen: 9 },
  { iso: 'TW', name: 'Taiwan', code: '+886', flag: '🇹🇼', lang: 'zh', minLen: 9, maxLen: 9 },
  { iso: 'TZ', name: 'Tanzania', code: '+255', flag: '🇹🇿', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'TH', name: 'Thailand', code: '+66', flag: '🇹🇭', lang: 'th', minLen: 9, maxLen: 9 },
  { iso: 'TN', name: 'Tunisia', code: '+216', flag: '🇹🇳', lang: 'ar', minLen: 8, maxLen: 8 },
  { iso: 'TR', name: 'Turkey', code: '+90', flag: '🇹🇷', lang: 'tr', minLen: 10, maxLen: 10 },
  { iso: 'UG', name: 'Uganda', code: '+256', flag: '🇺🇬', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'UA', name: 'Ukraine', code: '+380', flag: '🇺🇦', lang: 'ru', minLen: 9, maxLen: 9 },
  { iso: 'UY', name: 'Uruguay', code: '+598', flag: '🇺🇾', lang: 'es', minLen: 8, maxLen: 8 },
  { iso: 'UZ', name: 'Uzbekistan', code: '+998', flag: '🇺🇿', lang: 'ru', minLen: 9, maxLen: 9 },
  { iso: 'VE', name: 'Venezuela', code: '+58', flag: '🇻🇪', lang: 'es', minLen: 10, maxLen: 10 },
  { iso: 'VN', name: 'Vietnam', code: '+84', flag: '🇻🇳', lang: 'vi', minLen: 9, maxLen: 10 },
  { iso: 'YEM', name: 'Yemen', code: '+967', flag: '🇾🇪', lang: 'ar', minLen: 9, maxLen: 9 },
  { iso: 'ZM', name: 'Zambia', code: '+260', flag: '🇿🇲', lang: 'en', minLen: 9, maxLen: 9 },
  { iso: 'ZW', name: 'Zimbabwe', code: '+263', flag: '🇿🇼', lang: 'en', minLen: 9, maxLen: 9 }
];

export const POPULAR_COUNTRIES = WORLD_COUNTRIES.filter(c => c.isPopular);

export function findCountryByIso(isoCode) {
  if (!isoCode) return WORLD_COUNTRIES[2]; // Default India
  return WORLD_COUNTRIES.find(c => c.iso.toUpperCase() === isoCode.toUpperCase()) || WORLD_COUNTRIES[2];
}

export function findCountryByDialCode(dialCode) {
  if (!dialCode) return WORLD_COUNTRIES[2];
  const cleanCode = dialCode.startsWith('+') ? dialCode : `+${dialCode}`;
  return WORLD_COUNTRIES.find(c => c.code === cleanCode) || WORLD_COUNTRIES[2];
}
